### PR TITLE
Split Swarm and TheVoid projects.

### PR DESCRIPTION
**Pull request by shindo**
Merge #31 first.

### CODE REVIEW

**Comment by bioothod** [comment]
What is the purpose of this split?
It was deliberately created together that updating one piece forced to sync it with another.

**Comment by shindo** [comment]
First of all, TheVoid and Swarm are separate projects. TheVoid uses Swarm, but Swarm can be used on its own (and it's right now).

What's the point in bumping version of Swarm when you just changed something in TheVoid?
It's getting worse if you want to bump major version.

The pull request is about to actually separate projects and develop them independently.

If major version of Swarm will be bumped (which should be rare), you will be free to stay with previous major version of Swarm or move to the new one (now I'm talking about TheVoid).

**Comment by bioothod** [comment]
You have not answered the question, I can not accept this pull request.

If you think that versioning issue may be a reason, then you are very wrong.
Major version updates have to be rare - that is the whole point of having major version.

Having **just** the same single logger and event loop is way more significant for development purposes, than version number increase. And I can assure you, that you will stop updating one of the projects as soon as you are interested only in another.

**Comment by shindo** [comment]
Common interface for HTTP stuff (headers, request, response, url, etc.) and logger is ok.
And that's the point for separate Swarm.

Event loop is not common, it's urlfetcher's stuff.

From my point of view, such "tight coupling" of the projects is a mistake.
And "development purposes" can not be the only reason to think about.
Your libraries/packages are to be used by other people and convenience of use is important as well.

Currently TheVoid is seen as a main project and is rapidly developing (in comparison with Swarm/urlfetcher).
Thus, its versions (minor or major) are updated with no changes to Swarm/urlfetcher. And these "empty" updates of other projects complicate its use. 

Major version updates have to be rare -- that's true, but it happens.
Major updates of TheVoid must not affect urlfetcher and vice versa.

Major updates of Swarm will be extremely rare and when it'll happen corresponding updates of thevoid and urlfetcher will be performed.

To be honest, I haven't heard of any use of swarm-xml (do you really use it?), btw it doesn't use swarm.

**Comment by shindo** [comment]
Additionally, for "development purposes" it's possible to create common CMakeLists.txt that will build swarm first, point include directories to local swarm's headers and set rpath to created library. 
After that it will build thevoid/urlfetcher with these settings. 

It will give you the ability to develop and build all projects locally from the same source.

**Comment by bioothod** [comment]
Having single repository means packages will always be in sync.
So far I do not see any problem in fact, that you update minor version numbers and those changes only affect thevoid. Having rare major version updates is not an issue too - it is not even inconvenience, it is a plain project safety to have everything in sync.

You have ignored common code and common update argument, but I still remember how we switched to common logger. Project source base will not be split just because you increment versions which only contain thevoid changes.

**Comment by shindo** [comment]
Ok, I understood your point.

You see all these libraries as a whole project, but from my point of view it's wrong at this point of time.
TheVoid has nothing in common with urlfetcher but swarm. Swarm is just common utility library.

And for me these projects (thevoid, urlfetcher) can be developed independently.

**Pull request closed without merging**
