### PR TITLE
signal handling

### PR DESCRIPTION
**Pull request by shindo**
OK, let's try again.

----------------
Public Interface
================

One can register custom handlers for specific signal with the following function:
```(cpp)
int ioremap::thevoid::register_signal_handler(int signal_number, signal_handler_type handler)
```

Signal handler's signature:
```(cpp)
void handler(int signal_number, base_server* server)
```

This function returns 0 if registration was successful, and -1 otherwise.

Each signal may be registered only once.

When added signal is catched its associated handler will be invoked for each server within its separate thread (server's monitoring thread).

For each server, all registered signal handlers will be invoked from within single thread. But the same handler may be invoked concurrently for distinct servers.

One must not register their own signal handlers (with signal(), sigaction(), etc.) for added signals.

This function is thread-safe and may be called anytime.

----------------
Implementation
==============

- just before first signal's registration pipe will be opened. All received signals will be written to and can be read from the pipe (this is very close to what signalfd() does).

- for each registered signal native handler is registered that just writes received signals to the pipe.

- there's global set of "subscribed" servers with their io_services within which registered handlers will be invoked (each server's monitoring io_service is used for this task).

- all registered servers are asynchronously reading the pipe (within their io_services), and once some server reads signal number from the pipe, it notifies all registered io_services with this signal's handler.

- when server stops it deregisters itself from this global mechanics.

-------------------
Example (multiserver)
===================

multiserver accepts multiple configuration files as program arguments and creates multiple servers according to passed configs:
```(bash)
./multiserver server-1.json server-2.json
```

Each server supports only /ping.
    
Signals handled with thevoid's mechanics:
- SIGTERM, SIGINT signals stop servers
- SIGHUP signal reloads servers' configuration
- SIGUSR1, SIGUSR2 signals are ignored
    
And SIGALRM signal is handled "manually" (bypass thevoid's mechanics).

This example shows how one can use `register_signal_handler()` function to register their own handlers.
Moreover, this example shows that one can register their own signal handlers with `sigaction()` (bypass thevoid's mechanics).

----------------------
Summary
======================
One can register their own handlers within thevoid (handler will be called for each server within its separate monitoring thread that already exists).

One can register no handler within thevoid (just do not use `run_server()` and `register_signal_handler()`), and no signals will be handled by thevoid (even the pipe will not be created).

One can use standard methods to register signal handlers (`signal()`, `sigaction()`) for signals that are not registered with thevoid's `register_signal_handler()` function.

`register_signal_handler()` may be called from any thread and anytime (**that's why we do not use `signalfd()`**, this solution is more complicated, but we do not limit user with unnecessary constraints).

### CODE REVIEW

**Comment by bioothod** [comment]
You say that calling `register_signal_handler()` from any thread anytime is a limitation of `signalfd()`, but I do not see any limitation of calling signalfd from any thread. Requirement to block signals in any case is still valid.

Could it be simpler if you use `signalfd()` in thevoid internals and invoke signal handlers when signal arrived? Registering new signal handler would automatically block signals and if user had spawned some threads previously, it could be his problem anyway?

It would eliminate complex pipe mechanics and postponing signal handler invocation on behalf of user's server threads.

**Comment by shindo** [comment]
`signalfd()` can just eliminate pipe creation. User's servers threads still will read fd for received signals.

So, with `signalfd()` you will just simplify internal implementation (which should not really bother user) and limit user (let's do not say "it's your problem" if we can).

**Comment by bioothod** [comment]
There are exactly the same issues with signal blocking in both cases, so I do not see what user limitation you are talking about?

And why do you want to invoke signal handlers on behalf of user's server threads?

**Comment by shindo** [comment]
Proposed solution does not require registered signals to be blocked process-wide.
User is allowed to create threads before/after calling `register_signal_handler()`.
User is allowed to call `register_signal_handler()` from any thread.

I'm talking about these limitations.

**Comment by shindo** [comment]
Calling user's signal handlers from within server's thread does not put unnecessary constraints on these handlers -- registered handlers are just functions, one is allowed to use mutexes, etc.

**Comment by bioothod** [comment]
If you do not block signals process-wise, what prevents from registering another signal handler for the same signal and receiving signals in signal handler invoked by classical mechanism?

Limitations are exactly the same for `signalfd()`, but it eliminates complex internal states - just read signal in thevoid thread from appropriate file descriptor and invoke (list of) signal handlers, isn't it the simplest and bug free way?

**Comment by shindo** [comment]
It's not possible to block signal process-wide. The only way to do it is to call `sigprocmask()` from within the main thread before creating any other threads.

**Comment by shindo** [comment]
Compare these limitations:
- use thevoid's signal mechanics strictly before creating any threads.
- do not use `signal()`, `sigaction()` with signals that you have already registered with `register_signal_handler()`.

**Comment by bioothod** [comment]
If you do not use `signal()` and friends then there is no need in the first limitation. If you do use `signal()` and friends, you actually have to use the first limitation (although no one does that).

Even  more, since we provide user a way to register signal handlers, it is ok to force him not to use his own signal handlers. It is a real mess when some signal is invoked via X mechanism and the others via Y mechanism - if thevoid provides a way to register signal handlers, user should not register his own. Especially when thevoid does not force classical signal handler limitations.

Simple code works the best, it does not contain bugs and those which are yet to be discovered are simple to fix. A spaghetti of events read and written over a bunch of pipes for no reason is a place where subtle bugs will live (partial reads and writes, blocked operations, deadlocks) - hope, you agree it is better not to introduce a place where bugs are even possible.

My proposal is quite trivial - `signalfd()` for all signals, list of handlers, invoke them on behalf of thevoid thread, that's it - the simplest solution. We say that user should not mess with signals at all since thevoid will handle them for him, he has just to register a handler, that's it.

**Comment by shindo** [comment]
`signalfd()` has exactly the same limitations -- do not create any threads before registering signals with thevoid's mechanics.

Your solution will work, as well as the current one.

From now, if the public interface is ok (`register_signal_handler()`, handler's signature and handler's invocation policy), I ask you to accept the patch.
Internal implementation could (and will) be changed later.

**Comment by bioothod** [comment]
You are right, limitations are the same. But for me it doesn't really matter since thevoid will provide a better way to handle signals than classical handlers. We can just say 'you have to use thevoid signal interfaces' and that's it.

Interface is good, but practice shows that temporal internal implementation will not be quickly changed as soon as it is accepted. Please let's finish with it now, it is not really a major set of changes.

**Comment by shindo** [comment]
Your solution is not just "write it simplier".

Your solution adds some limitations (that do not matter probably), but I'm not ready to accept them:
- `signalfd()` limitation about child threads (*the major one*)
- limit user with thevoid's signal handling (do not use `signal()`, `sigaction()`)

I'm still trying to take into consideration "embedded" case, when one integrates thevoid's server into their application.
This way server may be created from different thread, not the main one. There may be signal handling already.
With the current solution one can use thevoid's signal handling (see it as helper here). Your solution does not allow this.

Maybe this use case is just a dream and your solution is the best one. But I don't think so.

Your point is that the current implementation is just complicated. Yes, it's not simple, but it does not put "unnecessary" limitations on its use.

**Comment by bioothod** [comment]
What do we want from thevoid signal subsystem? If we say that it is a better than classical signal handling mechanism, then it is thevoid who makes the rules.

Do not try to overengineer and overdesign the system, it must be as simple as possible.
You do not and really can not know in advance how system will ever be used, but you can design for particular use case. At least this will allow you to concentrate on a single path and extend it if necessary.

What you are afraid of - people who will use classical signal mechanism and thevoid one and multiple threads where signals are registered in advance - you do not know whether this is valid use case or not. And instead of building a simple system with a clear bugfree design you introduce a spaghetti of tricky cases which might in theory help in that one obscure unreal project.
That is not how systems are designed.

I'm against such peculiar cases, system must be generic. And thevoid is generic, thus no messy signal handling.

Generic systems have rules about how you can use them. And those rules may include 'do not use your own signals since it will mess with our signal, instead we provide you a BETTER way of doing this'. That's what I want from generic system, and not a set of spikes for particular theoretic cases.

Please implement simple signalfd() solution with API to register own signal handlers. Without pipes, postponing work and so on. I would even agree on dedicated thevoid thread for that (although it is a clear overhead). But do not introduce supposed-to-be-a-fix for unknown problem.

**Comment by shindo** [comment]
Reworked with signalfd().

Separate thread ("void_signal") is used to monitor received signals.

Now it's required to register all signal handlers before creating any threads.
One is not allowed to use `signal()`, `sigaction()`, etc. if they register signal handler with provided mechanics.

Once all handlers are registered one has to call `run_signal_thread()`.
To stop separate signal monitoring thread one has to call `stop_signal_thread()`.

**Comment by bioothod** [comment]
Looks good to me, thank you

**Comment by bioothod** [comment]
Should it be a new release?

**Comment by shindo** [comment]
It will be shortly.

**Pull request merged**
