### PR TITLE
Introduce functional tests

### PR DESCRIPTION
**Pull request by shindo**
Thevoid lacks of tests (actually, any kind of tests). This pull request introduces basic set of functional tests.

All tests run against `test_server` (tests/server.cpp). All handlers (tests/handlers/) are available to the server via REGISTER_HANDLER macro (see tests/handlers/ok.cpp).
Server's configuration is passed via `pytest.mark.server_options`, `test_server` starts with these options for each test (if server fixture is used).

### CODE REVIEW

**Comment by bioothod** [comment]
This needs a HUGE comment section which will describe tests, what are they doing, what do they expect, how they handle errors and so on

**Comment by shindo** [comment]
Yeah surely all tests must be well-documented and so on (and they will be).

The pull request is actually about "how to write tests" (test server, handlers, fixtures) and should be developed further before it can be applied.

Proposed tests are examples (but they're tests still) and probably will evolve to something more complex.
So this is the thing we should talk about - what to test (HTTP spec conformity, logs, internal state), how to use these functional tests in development process (TDD?).

**Comment by bioothod** [comment]
It doesn't make any help with test writing without actual understanding of what author meant by this and that test.
Examples MUST be documented first, since it is the code people look at to extend the project.

So I expect a major documentation update for this pull request to merge - this will be a serious step forward.

**Comment by shindo** [comment]
I'd like you to look through the patch once again.

There're several things that probably should be improved before these tests can be used as a post-build ones:
- if `port` or `monitor_port` is not specified with `server_options` mark, it will be chosen randomly. And this may spuriously fail (port is already in use), despite the fact that the port was checked
- server's logs are used for ensuring server's start (log level must be at least info) and may be used in some tests (here, reading log lines should be asynchronous to be able to fail test be timeout if sought-for line isn't in the log)

Also, I'd like to invite to the review: @ijon, @nobodyisme

**Pull request merged**
