### PR TITLE
migrate to blackhole v0.5

### PR DESCRIPTION
**Pull request by ndk**
do not accept, not tested yet, just review please

### CODE REVIEW

**Comment by shindo** [comment]
Well, I'll answer you about all this blackhole v0.5 thing here.

These changes break public API (and -dev package's dependencies, that also can be seen as breaking public API). Also, blackhole v0.2 and blackhole v0.5 packages are incompatible (their installation pathes are the same).

This means that we should bump major version (this applies to elliptics as well). And there're not enough breaking changes to the public API to do it right now.

**Comment by vitalyisaev2** [comment]
Thank you @ndk

@shindo, It would be really great to move to the recent version of blackhole library. Please, consider this PR again when there will be enough changes for another major release.

**Comment by shindo** [comment]
Well, that's kinda hard question because it's not only about swarm/thevoid.

There're other components that use thevoid, provided swarm's logger and blackhole. If thevoid moves to the recent version of blackhole these components should do the same. That's why this move must be accompanied with major version bump.

Swarm/thevoid's major version bump itself will require dependent components to update their dependencies (as swarm/thevoid packages include major version number in their names now) and bump a new version.
We should try our best to bump the major version as rare as possible. But still there should be no fanaticism.

Could you please explain why moving to the recent version of the blackhole library is needed in your use-case? We definitely will try to do it with the next major version bump, but your use-case may force the thing.

**Comment by ndk** [comment]
all our new components build with blackhole v0.5, but components like swarm still uses blackhole v0.2 and we have a headers conflict. as variant we can "submodulize" blackhole v0.2 into swarm.

**Comment by shindo** [comment]
To be honest, I don't like header-only logging library here. With every changes and fixes in the library, we have to recompile/update dependencies/update version of swarm/thevoid.
Still there're possible advantages of the header-only library (e.g., performance), but we pay for this with an ease of update.

From my point of view, it would be really great to have a shared library wrapper for the header-only version of the blackhole (that can be supported by the blackhole's dev team). And I expect this shared library to have a way more stable API.

And it will be user's (I mean the developer of some other library) decision whether to use the header-only version or the shared library based on their performance needs or whatever else.

**Comment by 3Hren** [comment]
Making the library shared and to stabilize its API - are orthogonal things. As like as all that "performane" shit and header-only libraries. Blackhole is stable enough right now.

Blackhole is a header-only mainly because of hundreds of templates. You can construct the logger of your dream using various policies (thread-safety, verbosity, fask-filtering, etc). However if you want to restrict N% of that functionality you can make a wrapper, which, you know, "stabilizes" your API, and to hide it over the shared library.

**Comment by shindo** [comment]
Yeah, I should state my thoughts more clearly.

BTW, there's appropriate issue on this problem already: https://github.com/3Hren/blackhole/issues/21
Let's keep the discussion there.

**Pull request closed without merging**
